### ISSUE TITLE
Help to setup please

### ISSUE THREAD

**Issue by IILucaII** [uditarora/cricket-umpire-assistance#2]
Hi.

I recently saw this project on github, and was so happy that I had found a ball-tracking app/software that I can use in my backyard. However, I have spent lots of hours trying to figure out how to use the gui as I encounter errors and this whole thing is confusing me. 
Output in cmd:

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python gui/gui.py
[INFO   ] [Logger      ] Record log in C:\Users\luca\.kivy\logs\kivy_19-08-05_4.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\luca\Anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\luca\Anaconda3\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 431.60'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "gui/gui.py", line 106, in <module>
     BTP().run()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\__init__.py", line 1402, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\__init__.py", line 1418, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\screenmanager.py", line 1191, in on_touch_down
     return super(ScreenManager, self).on_touch_down(touch)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\relativelayout.py", line 288, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\gui\layout.kv", line 83, in <module>
     on_press: root.open(filechooser.path, filechooser.selection)
   File "gui/gui.py", line 44, in open
     subprocess.call(["open", filename[0]])
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 323, in call
     with Popen(*popenargs, **kwargs) as p:
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 775, in __init__
     restore_signals, start_new_session)
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
     startupinfo)
 FileNotFoundError: [WinError 2] The system cannot find the file specified

This is a snippet of what my directories are:
![image](https://user-images.githubusercontent.com/46817881/62448503-95f1a900-b79a-11e9-9635-2502d3f5b9e6.png)

Im not sure what I need to do in order to use this.
Please help, and if you can, make a video on how to use this.

Thanks alot!

Luca

(BTW I am using python 3.7, and installed the dependencies, and also got anaconda3/miniconda.)

**Comment by uditarora** [comment]
Hi,

You'll need to update the directory where the videos are stored in the layout.kv file as well, as indicated by - 

"File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\gui\layout.kv", line 83, in"

Let me know if this helps, or if you face any other issues.

**Comment by IILucaII** [comment]
Hi!

So I updated the directory where my videos were stored, and it gave me this error 

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python gui/gui.py
[INFO   ] [Logger      ] Record log in C:\Users\luca\.kivy\logs\kivy_19-08-09_2.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\luca\Anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\luca\Anaconda3\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 431.60'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "gui/gui.py", line 106, in <module>
     BTP().run()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\__init__.py", line 1402, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\__init__.py", line 1418, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\screenmanager.py", line 1191, in on_touch_down
     return super(ScreenManager, self).on_touch_down(touch)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\relativelayout.py", line 288, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\gui\layout.kv", line 97, in <module>
     on_press: root.visualize()
   File "gui/gui.py", line 91, in visualize
     subprocess.call(["open", "-a", "Terminal", "./visualize.sh"])
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 323, in call
     with Popen(*popenargs, **kwargs) as p:
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 775, in __init__
     restore_signals, start_new_session)
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
     startupinfo)
 FileNotFoundError: [WinError 2] The system cannot find the file specified



When I click on visualise, it just closes the window. Please help

Thanks






















![image](https://user-images.githubusercontent.com/46817881/62762695-4b36a080-babc-11e9-9485-a8c72589d59a.png)

**Comment by IILucaII** [comment]
This error appears when I change the root path to the one found here
![image](https://user-images.githubusercontent.com/46817881/62763011-1414bf00-babd-11e9-8a32-392f1f3204e9.png)

And when I add that one to my layout.kv rootpath
![image](https://user-images.githubusercontent.com/46817881/62763049-31498d80-babd-11e9-91c7-0db6e6842fbf.png)

I am given an error saying:

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python gui/gui.py
[INFO   ] [Logger      ] Record log in C:\Users\luca\.kivy\logs\kivy_19-08-09_4.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\luca\Anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\luca\Anaconda3\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 431.60'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "gui/gui.py", line 22, in <module>
     Builder.load_file('layout.kv')
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 368, in load_string
     parser = Parser(content=string, filename=fn)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 401, in __init__
     self.parse(content)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 514, in parse
     rule.precompile()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 261, in precompile
     x.precompile()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 261, in precompile
     x.precompile()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 261, in precompile
     x.precompile()
   [Previous line repeated 1 more time]
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 257, in precompile
     x.precompile()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 179, in precompile
     self.co_value = eval(value)
   File "<string>", line 1
 SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape


With this error, the gui window will not appear.


Thanks

Luca

**Comment by IILucaII** [comment]
Sorry to bother you.

I tried changing it to double \ (like C:\\Users\\etc..) and it opened the gui. I click the video, and neither analyze, play video or visualize work.

comes up with an error like


C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python gui/gui.py
[INFO   ] [Logger      ] Record log in C:\Users\luca\.kivy\logs\kivy_19-08-09_8.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\luca\Anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\luca\Anaconda3\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 431.60'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "gui/gui.py", line 106, in <module>
     BTP().run()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 342, in idle
     self.dispatch_input()
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\base.py", line 233, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\__init__.py", line 1402, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\core\window\__init__.py", line 1418, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\screenmanager.py", line 1191, in on_touch_down
     return super(ScreenManager, self).on_touch_down(touch)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\relativelayout.py", line 288, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\widget.py", line 549, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "C:\Users\luca\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\gui\layout.kv", line 97, in <module>
     on_press: root.visualize()
   File "gui/gui.py", line 91, in visualize
     subprocess.call(["open", "-a", "Terminal", "./visualize.sh"])
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 323, in call
     with Popen(*popenargs, **kwargs) as p:
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 775, in __init__
     restore_signals, start_new_session)
   File "C:\Users\luca\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
     startupinfo)
 FileNotFoundError: [WinError 2] The system cannot find the file specified


I am so sorry to spam the thread.

Maybe if you make a video tutorial it might help?



Luca

**Comment by uditarora** [comment]
I see. The GUI relies on shell scripts for it to properly call the python files with the right set of arguments and the right paths.

And that piece of code is very MacOS specific right now, especially this line - 

`subprocess.call(["open", "-a", "Terminal", "./visualize.sh"])`

For Windows, a lot of changes will have to be made - replacing the shell scripts by the appropriate windows batch scripts and updating the subprocess.call statement.

**Comment by IILucaII** [comment]
Hmm. Am I able to run this whole thing in an apple/mac VM? Or do i have to change all of that scripty stuff?

**Comment by uditarora** [comment]
I don't think it is possible to setup a mac VM easily. It'll be better to change the scripts.

**Comment by IILucaII** [comment]
Could you? I dont know what Im doing :(

**Comment by IILucaII** [comment]
Or dyou have a mac?

**Comment by IILucaII** [comment]
Am I able to run the script without the gui - and will it work? Or is the whole script for macOS?

Thanks

**Comment by IILucaII** [comment]
To sum up, am I able to run this on windows, by installing bash shell on windows. Am I able to run this script on a linux VM? I dont know how to convert bash to a windows type. I really would like to run videos on here and use hawkeye. Is there any other possible way that I can run this without having to change the scripts? Thanks

**Comment by IILucaII** [comment]
Does this need macOS to run, or can you use a different OS like Linux, or Windows?

**Comment by uditarora** [comment]
It should work on Linux with minor modifications. But for Windows, it'll need a lot of changes. 

A quick workaround would be using the python files directly instead of relying on the GUI which internally runs those python scripts.

**Comment by IILucaII** [comment]
Tried that method, get this error

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python object-detector/ballTracking.py -v VP.mp4 -a 1
  File "object-detector/ballTracking.py", line 192
    print "Unable to grab frame: "+str(frame_no)
                                 ^
SyntaxError: invalid syntax

**Comment by uditarora** [comment]
This code was initially written for python 2. Hence this print statement for the older version of python.

You can simply fix this by adding brackets to the statement as follows -

`print("Unable to grab frame: "+str(frame_no))`

**Comment by IILucaII** [comment]
Fixed that problem, now i get this

C:\Users\luca\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "object-detector/ballTracking.py", line 9, in <module>
    import detector
  File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\object-detector\detector.py", line 8, in <module>
    from nms import nms
  File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\object-detector\nms.py", line 44
    return []
            ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by uditarora** [comment]
There seems to be a missing tab before that line. Just try adding one, since it is preceded by an if statement.

**Comment by IILucaII** [comment]
I got this error when I ran it:

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python object-detector/ballTracking.py -v VP.mp4
C:\Users\luca\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "object-detector/ballTracking.py", line 9, in <module>
    import detector
  File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\object-detector\detector.py", line 8, in <module>
    from nms import nms
  File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\object-detector\nms.py", line 43
    if len(detections) = 0:
                          ^
TabError: inconsistent use of tabs and spaces in indentation




Ill attach a picture of what my code looks like

![image](https://user-images.githubusercontent.com/46817881/63249218-98c0c380-c29b-11e9-8935-81fb3d921aa3.png)

**Comment by uditarora** [comment]
The line 

`if len(detections) == 0:`

needs to be unindented here.

**Comment by IILucaII** [comment]
Error here

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>python object-detector/balltracking.py -v VP.mp4
C:\Users\luca\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "object-detector/balltracking.py", line 9, in <module>
    import detector
  File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\object-detector\detector.py", line 8, in <module>
    from nms import nms
  File "C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master\object-detector\nms.py", line 46
    detections = sorted(detections, key=lambda detections: detections[2],
                                                                        ^
IndentationError: unindent does not match any outer indentation level

C:\Users\luca\Desktop\DesktopStuff\cricket-umpire-assistance-master>



Is it because Im on python 3?

Thanks

**Comment by uditarora** [comment]
Yeah, seems so.

I am able to run the code locally on my python 2 environment.

**Comment by aryan4559** [comment]
Could you please share the zip file of the running code and the video of the dataset? 
Please it's urgent .
Thank you
