### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by aydenbottos** [uditarora/cricket-umpire-assistance#3]
Traceback (most recent call last):
  File "ballTracking.py", line 416, in <module>
    found = findRadius(img_ball, current_ballPos[0], current_ballPos[1], frame_no)
  File "ballTracking.py", line 84, in findRadius
    avg_color_ball += blurredFrame[frame_center_y+dy][frame_center_x+dx]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I converted the script to Python 3. This error persists on other videos too.

**Comment by aydenbottos** [comment]
I also tried on Python 2 and it didn't work either.
